language: php
php:
    - 5.5
    - 5.4

script: "VERBOSE=true ./tests/run-tests.sh -s tests/"

services:
  - mongodb

before_script:
# Install Nette Tester
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --no-interaction --dev
